---
title: "DNAm age changes proportionate to genome size"
author: "Richard J. Acton"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_caption: yes
    number_sections: yes
    toc: yes
    toc_float: yes
    df_print: paged
    keep_md: yes
  html_notebook:
    fig_caption: yes
    number_sections: yes
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
    fig_caption: yes
    df_print: kable
bibliography: "`r normalizePath(params$bib)`"
csl: "`r normalizePath(params$csl)`"
link-citations: yes
linkcolor: blue
#runtime: shiny
editor_options: 
  chunk_output_type: inline
params:
  bib: "../library.bib"
  csl: "../genomebiology.csl"
  inFile: "out/nSigWinProps_WGfishers_BB_sws_hyper_2_BL.tsv"
---

# Set-up

## Libs

```{r}
suppressPackageStartupMessages({
	library(tidyverse)
	library(magrittr)
	library(ggsignif)
	library(tidytext)
})
```

```{r}
nm <- gsub(params$inFile, pattern = ".*\\/(.*)\\.tsv", replacement = "\\1")
nm <- paste0(nm, "_noPolyBivExcl")
outDir <- glue::glue("graphics/{nm}")
if(!dir.exists(outDir)) {dir.create(outDir)}
```

# Data Read-in

```{r}
# enrich <- read_tsv("../out/nSigWinProps_BB_2.tsv") %>%
enrich <- read_tsv(params$inFile) %>%
	
	tidyr::extract(
		col = testSet, #name,
		into = c("model", "sig", "feature", "dir"),
		regex = "(\\w+)_(\\w+)_(\\w+)_([+-]|(?:either))"
	) %>%
	mutate(pc = prop * 100) %>%
	mutate(
		sigLevAstr = case_when(
			p.value < 0.001 ~ "***", 
			p.value < 0.01 ~ "**",
			TRUE ~ ""
		)
	)
enrich
```

```{r}
enrich <- 
enrich %>% 
	filter(feature %in% c("tRNAs", "WholeGenome", "promoters", "CGI", "exons"))# %>%
	# mutate(
	# 	feature = case_when(
	# 		feature == "tRNAsNoPolyBivP" ~ "tRNAs",
	# 		#feature == "bivalentPromP" ~ "bivalent",
	# 		TRUE ~ feature
	# 	)
	# )
```


```{r, fig.width = 16, fig.asp = 9/16}
enrich %>% 
	mutate(featurer = tidytext::reorder_within(feature, dplyr::desc(pc), dir)) %>%
	ggplot(aes(featurer, pc)) + 
	geom_col(aes(fill = feature), show.legend = FALSE) + 
	geom_text(
		aes(
			label = paste0(
				format(nSig, big.mark = ","), " /",
				format(nWins, big.mark = ",")
			)
		),
		vjust = -0.3
	) + 
	scale_x_reordered() +
	labs(
		title = "Significant Age Related Changes",
		subtitle = "Percentage of significant windows by feature type",
		x = "Feature",
		y = "% Significant"
	) + 
	theme_bw() +
	facet_grid(sig ~ dir, scales = "free")
```

```{r, fig.width = 7, fig.height = 5}
gwsHyperBar <- 
enrich %>% 
	# filter(sig == "gws", dir == "+") %>%
	mutate(featurer = tidytext::reorder_within(feature, dplyr::desc(pc), dir)) %>%
	ggplot(aes(featurer,pc)) + 
	geom_col(aes(fill = feature), show.legend = FALSE) + 
	scale_x_reordered() +
	labs(
		title = "Significant Age Related Hypermethylation",
		subtitle = "Percentage of significant windows by feature type",
		x = "Feature",
		y = "% Significant"
	) + 
	theme_bw() #+
# 	theme(axis.text.x = element_text(angle = 90))

gwsHyperBarTxtast <- 
	gwsHyperBar + 
	geom_text(
		aes(
			label = sigLevAstr,
		),
		vjust = -0.3
	)

gwsHyperBarTxtast
```

```{r}
if(!dir.exists("graphics")) {
	dir.create("graphics", showWarnings = FALSE, recursive = TRUE)
}
```

```{r}
ggsave(
	plot = gwsHyperBarTxtast,
	filename = glue::glue("graphics/{nm}/{nm}_BarTxtast_sr.png"),
	width = 7,
	height = 5
)
```

```{r, fig.width = 7, fig.height = 5}
gwsHyperBar <- 
enrich %>% 
	# filter(sig == "gws", dir == "+") %>%
	mutate(featurer = tidytext::reorder_within(feature,dplyr::desc(pc),dir)) %>%
	ggplot(aes(featurer,pc)) + 
	geom_col(aes(fill = feature),show.legend = FALSE) + 
	scale_x_reordered() +
	labs(
		title = "Significant Age Related Hypermethylation",
		subtitle = "Percentage of significant windows by feature type",
		x = "Feature",
		y = "% Significant"
	) + 
	theme_bw() #+ 
#	theme(axis.text.x = element_text(angle = 90))
	#facet_grid(sig~dir, scales = "free")

gwsHyperBarTxt <- 
	gwsHyperBar + 
	geom_text(
		aes(
			label = paste0(
				format(nSig,big.mark=","), " /",
				format(nWins,big.mark = ",")
			)
		),
		vjust = -0.3,
		size = 2
	)

gwsHyperBarTxt
```

```{r}
ggsave(
	plot = gwsHyperBarTxt,
	filename = glue::glue("graphics/{nm}/{nm}_BarTxt_sr.png"),
	width = 7,
	height = 5
)
ggsave(
	plot = gwsHyperBar,
	filename = glue::glue("graphics/{nm}/{nm}_Bar_sr.png"),
	width = 7,
	height = 5
)
```

# Session Info

```{r}
sessionInfo()
```

# References

